name: sleep
channels:
  - conda-forge
  - bioconda
  - R
dependencies:
  - r-base=4.2.2
  - r-tidyverse=1.3.1
  - r-feather=0.3.5
  - r-arrow=9.0.0
  - r-janitor=2.1.0
  # - r-read.cwa install from github!
  - r-tidymodels=1.0.0
  - r-beepr
  - r-doParallel
  - r-pls
  - r-mixOmics
  - r-earth
  - r-stringi=1.7.8
  - r-xgboost
  - r-lme4
  - r-devtools
  - r-janitor
  - r-liblinear
  - r-ranger
  - r-shape
  - r-glmnet
  - r-kernlab
  - r-kknn
  - r-baguette
  - r-stacks
  - r-BBmisc
  - r-signal
  - r-keras
  - r-feasts
  - r-tsibble
  - r-essentials
  - r-rpart.plot=3.1.1
  - r-patchwork
  - r-svglite=2.1.0
  - r-showtext=0.9_5
  - quarto=1.1.145
  - snakemake=7.18.2
  - graphviz=6.0.1
  - cudatoolkit=11.3.1
  - yasa=0.6.2
  - mne=1.2.1
  - gcc=12.1.0
  - lightgbm=3.3.3
  # - morfist
  - tensorflow
