name: sleep
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.2.1
  - r-tidyverse=1.3.1
  - r-feather=0.3.5
  - r-arrow=9.0.0.2
  - r-janitor=2.1.0
  - r-read.cwa=0.2.1
  - quarto=1.1.145
  - r-stringi=1.7.8
  - snakemake=7.14.0
  - graphviz=6.0.1
